import { RootProviders } from '@/provider/root-provider';
import type { Metadata } from 'next';
import { Geist, Raleway } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const railway = Raleway({
  variable: '--font-railway',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RootProviders>
        <body
          className={`${geistSans.variable} ${railway.variable} antialiased`}
        >
          {children}
          <Toaster position="top-right" />
        </body>
      </RootProviders>
    </html>
  );
}
