import { RootProviders } from '@/provider/root-provider';
import type { Metadata } from 'next';
import { Geist, Raleway } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

// Load Geist Sans font for general UI elements
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

// Load Raleway font as the primary font for the application
const railway = Raleway({
  variable: '--font-railway',
  subsets: ['latin'],
});

// Metadata for SEO and browser display
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Root layout wrapper
 * @param children - All page components will be rendered as children
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* RootProviders wraps the app with necessary context providers (e.g., Redux, React Query) */}
      <RootProviders>
        <body
          className={`${geistSans.variable} ${railway.variable} antialiased`}
        >
          {/* Render all page content */}
          {children}
          {/* Toast notification component for user feedback */}
          <Toaster position="top-right" />
        </body>
      </RootProviders>
    </html>
  );
}
